development:
  adapter: postgresql
  encoding: utf8
  database: appfunnel_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: appfunnel_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: appfunnel_production
  pool: 5
  username: 
  password:
